[package]
name = "xml_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
flutter_rust_bridge = { path = "../../../../../frb_rust" }
serde = { version = "1.0.210", features = ["derive"] }
quick-xml = { version = "0.36.2", features = ["serialize"] }
serde-value = "0.7.0"